name: Node.js Test CI
on:
  push:
    branches: 
      - "**"
  pull_request:
    branches:
      - "**"
  schedule:
    - cron: "45 10 12,24 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run test
      env:
        ID: ${{ secrets.OSU_ID }}
        SECRET: ${{ secrets.OSU_SECRET }}
